import sys
import re
filename = sys.argv[1]
with open(filename, 'r') as content_file:
    content = content_file.read()
    result = re.sub(r"Inductive", "type", content, 0, re.DOTALL)
    result = re.sub(r": Type", "", result, 0, re.DOTALL)
    result = re.sub(r":=", "=", result, 0, re.DOTALL)
    result = re.sub(r"=>", "->", result, 0, re.DOTALL)
    result = re.sub(r"=>", "->", result, 0, re.DOTALL)
    result = re.sub(r"Instruction", "instruction", result, 0, re.DOTALL)
    result = re.sub(r"OpCode", "op_code", result, 0, re.DOTALL)
    result = re.sub(r"OpCodes", "op_codes", result, 0, re.DOTALL)
    result = re.sub(r"end\.", "", result, 0, re.DOTALL)
    result = re.sub(r"Definition", "let", result, 0, re.DOTALL)
    result = re.sub(r"Fixpoint", "let rec", result, 0, re.DOTALL)
    result = re.sub(r"Label", "label", result, 0, re.DOTALL)
    result = re.sub(r"LAB", "lab", result, 0, re.DOTALL)
    result = re.sub(r"lab n", "lab", result, 0, re.DOTALL)
    result = re.sub(r"rule_scond n", "rule_scond", result, 0, re.DOTALL)
    result = re.sub(r"rule_expr n", "rule_expr", result, 0, re.DOTALL)
    result = re.sub(r"AllowModify", "allow_modify", result, 0, re.DOTALL)
    result = re.sub(r"allow_modify n", "allow_modify", result, 0, re.DOTALL)
    result = re.sub(r"{A:Type}", "", result, 0, re.DOTALL)
    result = re.sub(r"nat", "int", result, 0, re.DOTALL)
    result = re.sub(r"Atom", "atom", result, 0, re.DOTALL)
    result = re.sub(r"Stack", "stack", result, 0, re.DOTALL)
    result = re.sub(r"State", "state", result, 0, re.DOTALL)
    result = re.sub(r"insert_nat", "insertRet", result, 0, re.DOTALL)
    print(result)
